# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-27 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.ImageField(default='ad/default.png', upload_to='./ad/%Y/%m', verbose_name='\u56fe\u7247url'),
        ),
    ]
