 # -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-27 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170927_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.ImageField(default='ad/default.png', upload_to='./ad/%Y/%m', verbose_name='\u56fe\u7247url'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', max_length=200, upload_to='./avatar/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
